export const GET_VACCINES = "GET_VACCINES";
export const GET_VACCINES_SUCCESS = "GET_VACCINES_SUCCESS";
export const GET_VACCINES_FAILED = "GET_VACCINES_FAILED";

export const GET_VACCINATION_CENTRES = "GET_VACCINATION_CENTRES";
export const GET_VACCINATION_CENTRES_SUCCESS =
  "GET_VACCINATION_CENTRES_SUCCESS";
export const GET_VACCINATION_CENTRES_FAILED = "GET_VACCINATION_CENTRES_FAILED";

export const GET_SCHEDULED_VACCINATION_CENTRES =
  "GET_SCHEDULED_VACCINATION_CENTRES";
export const GET_SCHEDULED_VACCINATION_CENTRES_SUCCESS =
  "GET_SCHEDULED_VACCINATION_CENTRES_SUCCESS";
export const GET_SCHEDULED_VACCINATION_CENTRES_FAILED =
  "GET_SCHEDULED_VACCINATION_CENTRES_FAILED";

export const GET_VACCINE_APPOINTMENTS = "GET_VACCINE_APPOINTMENTS";
export const GET_VACCINE_APPOINTMENTS_SUCCESS =
  "GET_VACCINE_APPOINTMENTS_SUCCESS";
export const GET_VACCINE_APPOINTMENTS_FAILED =
  "GET_VACCINE_APPOINTMENTS_FAILED";

export const GET_PANDEMIC_VACCINATIONS = "GET_PANDEMIC_VACCINATIONS";
export const GET_PANDEMIC_VACCINATIONS_SUCCESS =
  "GET_PANDEMIC_VACCINATIONS_SUCCESS";
export const GET_PANDEMIC_VACCINATIONS_FAILED =
  "GET_PANDEMIC_VACCINATIONS_FAILED";

export const GET_VACCINE_BY_ID = "GET_VACCINE_BY_ID";
export const GET_VACCINE_BY_ID_SUCCESS = "GET_VACCINE_BY_ID_SUCCESS";
export const GET_VACCINE_BY_ID_FAILED = "GET_VACCINE_BY_ID_FAILED";

export const GET_VACCINATION_CENTRE_BY_ID = "GET_VACCINATION_CENTRE_BY_ID";
export const GET_VACCINATION_CENTRE_BY_ID_SUCCESS =
  "GET_VACCINATION_CENTRE_BY_ID_SUCCESS";
export const GET_VACCINATION_CENTRE_BY_ID_FAILED =
  "GET_VACCINATION_CENTRE_BY_ID_FAILED";

export const GET_SCHEDULED_VACCINATION_CENTRE_BY_ID =
  "GET_SCHEDULED_VACCINATION_CENTRE_BY_ID";
export const GET_SCHEDULED_VACCINATION_CENTRE_BY_ID_SUCCESS =
  "GET_SCHEDULED_VACCINATION_CENTRE_BY_ID_SUCCESS";
export const GET_SCHEDULED_VACCINATION_CENTRE_BY_ID_FAILED =
  "GET_SCHEDULED_VACCINATION_CENTRE_BY_ID_FAILED";

export const GET_VACCINE_APPOINTMENT_BY_ID = "GET_VACCINE_APPOINTMENT_BY_ID";
export const GET_VACCINE_APPOINTMENT_BY_ID_SUCCESS =
  "GET_VACCINE_APPOINTMENT_BY_ID_SUCCESS";
export const GET_VACCINE_APPOINTMENT_BY_ID_FAILED =
  "GET_VACCINE_APPOINTMENT_BY_ID_FAILED";

export const GET_PANDEMIC_VACCINATION_BY_ID = "GET_PANDEMIC_VACCINATION_BY_ID";
export const GET_PANDEMIC_VACCINATION_BY_ID_SUCCESS =
  "GET_PANDEMIC_VACCINATION_BY_ID_SUCCESS";
export const GET_PANDEMIC_VACCINATION_BY_ID_FAILED =
  "GET_PANDEMIC_VACCINATION_BY_ID_FAILED";

export const POST_VACCINE = "POST_VACCINE";
export const POST_VACCINE_SUCCESS = "POST_VACCINE_SUCCESS";
export const POST_VACCINE_FAILED = "POST_VACCINE_FAILED";

export const POST_VACCINATION_CENTRE = "POST_VACCINATION_CENTRE";
export const POST_VACCINATION_CENTRE_SUCCESS =
  "POST_VACCINATION_CENTRE_SUCCESS";
export const POST_VACCINATION_CENTRE_FAILED = "POST_VACCINATION_CENTRE_FAILED";

export const POST_SCHEDULED_VACCINATION_CENTRE =
  "POST_SCHEDULED_VACCINATION_CENTRE";
export const POST_SCHEDULED_VACCINATION_CENTRE_SUCCESS =
  "POST_SCHEDULED_VACCINATION_CENTRE_SUCCESS";
export const POST_SCHEDULED_VACCINATION_CENTRE_FAILED =
  "POST_SCHEDULED_VACCINATION_CENTRE_FAILED";

export const POST_VACCINE_APPOINTMENT = "POST_VACCINE_APPOINTMENT";
export const POST_VACCINE_APPOINTMENT_SUCCESS =
  "POST_VACCINE_APPOINTMENT_SUCCESS";
export const POST_VACCINE_APPOINTMENT_FAILED =
  "POST_VACCINE_APPOINTMENT_FAILED";

export const POST_PANDEMIC_VACCINATION = "POST_PANDEMIC_VACCINATION";
export const POST_PANDEMIC_VACCINATION_SUCCESS =
  "POST_PANDEMIC_VACCINATION_SUCCESS";
export const POST_PANDEMIC_VACCINATION_FAILED =
  "POST_PANDEMIC_VACCINATION_FAILED";

export const PUT_VACCINE = "PUT_VACCINE";
export const PUT_VACCINE_SUCCESS = "PUT_VACCINE_SUCCESS";
export const PUT_VACCINE_FAILED = "PUT_VACCINE_FAILED";

export const PUT_VACCINATION_CENTRE = "PUT_VACCINATION_CENTRE";
export const PUT_VACCINATION_CENTRE_SUCCESS = "PUT_VACCINATION_CENTRE_SUCCESS";
export const PUT_VACCINATION_CENTRE_FAILED = "PUT_VACCINATION_CENTRE_FAILED";

export const PUT_SCHEDULED_VACCINATION_CENTRE =
  "PUT_SCHEDULED_VACCINATION_CENTRE";
export const PUT_SCHEDULED_VACCINATION_CENTRE_SUCCESS =
  "PUT_SCHEDULED_VACCINATION_CENTRE_SUCCESS";
export const PUT_SCHEDULED_VACCINATION_CENTRE_FAILED =
  "PUT_SCHEDULED_VACCINATION_CENTRE_FAILED";

export const PUT_VACCINE_APPOINTMENT = "PUT_VACCINE_APPOINTMENT";
export const PUT_VACCINE_APPOINTMENT_SUCCESS =
  "PUT_VACCINE_APPOINTMENT_SUCCESS";
export const PUT_VACCINE_APPOINTMENT_FAILED = "PUT_VACCINE_APPOINTMENT_FAILED";

export const PUT_PANDEMIC_VACCINATION = "PUT_PANDEMIC_VACCINATION";
export const PUT_PANDEMIC_VACCINATION_SUCCESS =
  "PUT_PANDEMIC_VACCINATION_SUCCESS";
export const PUT_PANDEMIC_VACCINATION_FAILED =
  "PUT_PANDEMIC_VACCINATION_FAILED";

export const GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO =
  "GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO";
export const GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO_SUCCESS =
  "GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO_SUCCESS";
export const GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO_FAILED =
  "GET_SCHEDULED_VACCINATION_CENTRES_BY_INFO_FAILED";
