export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENTS_SUCCESS = "GET_PATIENTS_SUCCESS";
export const GET_PATIENTS_FAILED = "GET_PATIENTS_FAILED";

export const GET_PATIENTS_OVERALL_STATS = "GET_PATIENTS_OVERALL_STATS";
export const GET_PATIENTS_OVERALL_STATS_SUCCESS =
  "GET_PATIENTS_OVERALL_STATS_SUCCESS";
export const GET_PATIENTS_OVERALL_STATS_FAILED =
  "GET_PATIENTS_OVERALL_STATS_FAILED";

export const GET_PATIENTS_MONTHLY_CONFIRMED_STATS =
  "GET_PATIENTS_MONTHLY_CONFIRMED_STATS";
export const GET_PATIENTS_MONTHLY_CONFIRMED_STATS_SUCCESS =
  "GET_PATIENTS_MONTHLY_CONFIRMED_STATS_SUCCESS";
export const GET_PATIENTS_MONTHLY_CONFIRMED_STATS_FAILED =
  "GET_PATIENTS_MONTHLY_CONFIRMED_STATS_FAILED";

export const GET_PATIENT_BY_ID = "GET_PATIENT_BY_ID";
export const GET_PATIENT_BY_ID_SUCCESS = "GET_PATIENT_BY_ID_SUCCESS";
export const GET_PATIENT_BY_ID_FAILED = "GET_PATIENT_BY_ID_FAILED";

export const CREATE_COVID_PATIENT = "CREATE_COVID_PATIENT";
export const CREATE_COVID_PATIENT_SUCCESS = "CREATE_COVID_PATIENT_SUCCESS";
export const CREATE_COVID_PATIENT_FAILED = "CREATE_COVID_PATIENT_FAILED";

export const UPDATE_COVID_PATIENT = "UPDATE_COVID_PATIENT";
export const UPDATE_COVID_PATIENT_SUCCESS = "UPDATE_COVID_PATIENT_SUCCESS";
export const UPDATE_COVID_PATIENT_FAILED = "UPDATE_COVID_PATIENT_FAILED";

export const GET_HOSPITALS = "GET_HOSPITALS";
export const GET_HOSPITALS_SUCCESS = "GET_HOSPITALS_SUCCESS";
export const GET_HOSPITALS_FAILED = "GET_HOSPITALS_FAILED";

export const GET_HOSPITAL_BY_ID = "GET_HOSPITAL_BY_ID";
export const GET_HOSPITAL_BY_ID_SUCCESS = "GET_HOSPITAL_BY_ID_SUCCESS";
export const GET_HOSPITAL_BY_ID_FAILED = "GET_HOSPITAL_BY_ID_FAILED";

export const CREATE_HOSPITAL = "CREATE_HOSPITAL";
export const CREATE_HOSPITAL_SUCCESS = "CREATE_HOSPITAL_SUCCESS";
export const CREATE_HOSPITAL_FAILED = "CREATE_HOSPITAL_FAILED";

export const UPDATE_HOSPITAL = "UPDATE_HOSPITAL";
export const UPDATE_HOSPITAL_SUCCESS = "UPDATE_HOSPITAL_SUCCESS";
export const UPDATE_HOSPITAL_FAILED = "UPDATE_HOSPITAL_FAILED";

export const GET_GOV_OFFICERS_IN_CHARGE = "GET_GOV_OFFICERS_IN_CHARGE";
export const GET_GOV_OFFICERS_IN_CHARGE_SUCCESS =
  "GET_GOV_OFFICERS_IN_CHARGE_SUCCESS";
export const GET_GOV_OFFICERS_IN_CHARGE_FAILED =
  "GET_GOV_OFFICERS_IN_CHARGE_FAILED";

export const GET_GOV_OFFICERS_IN_CHARGE_BY_ID =
  "GET_GOV_OFFICERS_IN_CHARGE_BY_ID";
export const GET_GOV_OFFICERS_IN_CHARGE_BY_ID_SUCCESS =
  "GET_GOV_OFFICERS_IN_CHARGE_BY_ID_SUCCESS";
export const GET_GOV_OFFICERS_IN_CHARGE_BY_ID_FAILED =
  "GET_GOV_OFFICERS_IN_CHARGE_BY_ID_FAILED";

export const CREATE_GOV_OFFICERS_IN_CHARGE = "CREATE_GOV_OFFICERS_IN_CHARGE";
export const CREATE_GOV_OFFICERS_IN_CHARGE_SUCCESS =
  "CREATE_GOV_OFFICERS_IN_CHARGE_SUCCESS";
export const CREATE_GOV_OFFICERS_IN_CHARGE_FAILED =
  "CREATE_GOV_OFFICERS_IN_CHARGE_FAILED";

export const UPDATE_GOV_OFFICERS_IN_CHARGE = "UPDATE_GOV_OFFICERS_IN_CHARGE";
export const UPDATE_GOV_OFFICERS_IN_CHARGE_SUCCESS =
  "UPDATE_GOV_OFFICERS_IN_CHARGE_SUCCESS";
export const UPDATE_GOV_OFFICERS_IN_CHARGE_FAILED =
  "UPDATE_GOV_OFFICERS_IN_CHARGE_FAILED";

export const GET_HEALTHCARE_PROFESSIONALS = "GET_HEALTHCARE_PROFESSIONALS";
export const GET_HEALTHCARE_PROFESSIONALS_SUCCESS =
  "GET_HEALTHCARE_PROFESSIONALS_SUCCESS";
export const GET_HEALTHCARE_PROFESSIONALS_FAILED =
  "GET_HEALTHCARE_PROFESSIONALS_FAILED";

export const GET_HEALTHCARE_PROFESSIONAL_BY_ID =
  "GET_HEALTHCARE_PROFESSIONAL_BY_ID";
export const GET_HEALTHCARE_PROFESSIONAL_BY_ID_SUCCESS =
  "GET_HEALTHCARE_PROFESSIONAL_BY_ID_SUCCESS";
export const GET_HEALTHCARE_PROFESSIONAL_BY_ID_FAILED =
  "GET_HEALTHCARE_PROFESSIONAL_BY_ID_FAILED";

export const CREATE_HEALTHCARE_PROFESSIONAL = "CREATE_HEALTHCARE_PROFESSIONAL";
export const CREATE_HEALTHCARE_PROFESSIONAL_SUCCESS =
  "CREATE_HEALTHCARE_PROFESSIONAL_SUCCESS";
export const CREATE_HEALTHCARE_PROFESSIONAL_FAILED =
  "CREATE_HEALTHCARE_PROFESSIONAL_FAILED";

export const UPDATE_HEALTHCARE_PROFESSIONAL = "UPDATE_HEALTHCARE_PROFESSIONAL";
export const UPDATE_HEALTHCARE_PROFESSIONAL_SUCCESS =
  "UPDATE_HEALTHCARE_PROFESSIONAL_SUCCESS";
export const UPDATE_HEALTHCARE_PROFESSIONAL_FAILED =
  "UPDATE_HEALTHCARE_PROFESSIONAL_FAILED";

export const GET_MEDICAL_HISTORIES_BY_ID = "GET_MEDICAL_HISTORIES_BY_ID";
export const GET_MEDICAL_HISTORIES_BY_ID_SUCCESS =
  "GET_MEDICAL_HISTORIES_BY_ID_SUCCESS";
export const GET_MEDICAL_HISTORIES_BY_ID_FAILED =
  "GET_MEDICAL_HISTORIES_BY_ID_FAILED";

export const CREATE_MEDICAL_HISTORY = "CREATE_MEDICAL_HISTORY";
export const CREATE_MEDICAL_HISTORY_SUCCESS = "CREATE_MEDICAL_HISTORY_SUCCESS";
export const CREATE_MEDICAL_HISTORY_FAILED = "CREATE_MEDICAL_HISTORY_FAILED";

export const GET_PATIENTS_BY_GOVERNMENT_IN_CHARGE =
  "GET_PATIENTS_BY_GOVERNMENT_IN_CHARGE";
export const GET_PATIENTS_BY_GOVERNMENT_IN_CHARGE_SUCCESS =
  "GET_PATIENTS_BY_GOVERNMENT_IN_CHARGE_SUCCESS";
export const GET_PATIENTS_BY_GOVERNMENT_IN_CHARGE_FAILED =
  "GET_PATIENTS_BY_GOVERNMENT_IN_CHARGE_FAILED";

export const GET_PATIENTS_BY_HEALTHCARE_PROFESSIONAL =
  "GET_PATIENTS_BY_HEALTHCARE_PROFESSIONAL";
export const GET_PATIENTS_BY_HEALTHCARE_PROFESSIONAL_SUCCESS =
  "GET_PATIENTS_BY_HEALTHCARE_PROFESSIONAL_SUCCESS";
export const GET_PATIENTS_BY_HEALTHCARE_PROFESSIONAL_FAILED =
  "GET_PATIENTS_BY_HEALTHCARE_PROFESSIONAL_FAILED";
