export const GET_TESTINGS = "GET_TESTINGS";
export const GET_TESTINGS_SUCCESS = "GET_TESTINGS_SUCCESS";
export const GET_TESTINGS_FAILED = "GET_TESTINGS_FAILED";

export const GET_TEST_CENTRES = "GET_TEST_CENTRES";
export const GET_TEST_CENTRES_SUCCESS = "GET_TEST_CENTRES_SUCCESS";
export const GET_TEST_CENTRES_FAILED = "GET_TEST_CENTRES_FAILED";

export const GET_SCHEDULED_TEST_CENTRES = "GET_SCHEDULED_TEST_CENTRES";
export const GET_SCHEDULED_TEST_CENTRES_SUCCESS =
  "GET_SCHEDULED_TEST_CENTRES_SUCCESS";
export const GET_SCHEDULED_TEST_CENTRES_FAILED =
  "GET_SCHEDULED_TEST_CENTRES_FAILED";

export const GET_TESTS_APPOINTMENTS = "GET_TESTS_APPOINTMENTS";
export const GET_TESTS_APPOINTMENTS_SUCCESS = "GET_TESTS_APPOINTMENTS_SUCCESS";
export const GET_TESTS_APPOINTMENTS_FAILED = "GET_TESTS_APPOINTMENTS_FAILED";

export const GET_PANDEMIC_TEST_RESULTS = "GET_PANDEMIC_TEST_RESULTS";
export const GET_PANDEMIC_TEST_RESULTS_SUCCESS =
  "GET_PANDEMIC_TEST_RESULTS_SUCCESS";
export const GET_PANDEMIC_TEST_RESULTS_FAILED =
  "GET_PANDEMIC_TEST_RESULTS_FAILED";

export const GET_TESTING_BY_ID = "GET_TESTING_BY_ID";
export const GET_TESTING_BY_ID_SUCCESS = "GET_TESTING_BY_ID_SUCCESS";
export const GET_TESTING_BY_ID_FAILED = "GET_TESTING_BY_ID_FAILED";

export const GET_TEST_CENTRE_BY_ID = "GET_TEST_CENTRE_BY_ID";
export const GET_TEST_CENTRE_BY_ID_SUCCESS = "GET_TEST_CENTRE_BY_ID_SUCCESS";
export const GET_TEST_CENTRE_BY_ID_FAILED = "GET_TEST_CENTRE_BY_ID_FAILED";

export const GET_SCHEDULED_TEST_CENTRE_BY_ID =
  "GET_SCHEDULED_TEST_CENTRE_BY_ID";
export const GET_SCHEDULED_TEST_CENTRE_BY_ID_SUCCESS =
  "GET_SCHEDULED_TEST_CENTRE_BY_ID_SUCCESS";
export const GET_SCHEDULED_TEST_CENTRE_BY_ID_FAILED =
  "GET_SCHEDULED_TEST_CENTRE_BY_ID_FAILED";

export const GET_TESTS_APPOINTMENT_BY_ID = "GET_TESTS_APPOINTMENT_BY_ID";
export const GET_TESTS_APPOINTMENT_BY_ID_SUCCESS =
  "GET_TESTS_APPOINTMENT_BY_ID_SUCCESS";
export const GET_TESTS_APPOINTMENT_BY_ID_FAILED =
  "GET_TESTS_APPOINTMENT_BY_ID_FAILED";

export const GET_PANDEMIC_TEST_RESULT_BY_ID = "GET_PANDEMIC_TEST_RESULT_BY_ID";
export const GET_PANDEMIC_TEST_RESULT_BY_ID_SUCCESS =
  "GET_PANDEMIC_TEST_RESULT_BY_ID_SUCCESS";
export const GET_PANDEMIC_TEST_RESULT_BY_ID_FAILED =
  "GET_PANDEMIC_TEST_RESULT_BY_ID_FAILED";

export const POST_TESTING = "POST_TESTING";
export const POST_TESTING_SUCCESS = "POST_TESTING_SUCCESS";
export const POST_TESTING_FAILED = "POST_TESTING_FAILED";

export const POST_TEST_CENTRE = "POST_TEST_CENTRE";
export const POST_TEST_CENTRE_SUCCESS = "POST_TEST_CENTRE_SUCCESS";
export const POST_TEST_CENTRE_FAILED = "POST_TEST_CENTRE_FAILED";

export const POST_SCHEDULED_TEST_CENTRE = "POST_SCHEDULED_TEST_CENTRE";
export const POST_SCHEDULED_TEST_CENTRE_SUCCESS =
  "POST_SCHEDULED_TEST_CENTRE_SUCCESS";
export const POST_SCHEDULED_TEST_CENTRE_FAILED =
  "POST_SCHEDULED_TEST_CENTRE_FAILED";

export const POST_TESTS_APPOINTMENT = "POST_TESTS_APPOINTMENT";
export const POST_TESTS_APPOINTMENT_SUCCESS = "POST_TESTS_APPOINTMENT_SUCCESS";
export const POST_TESTS_APPOINTMENT_FAILED = "POST_TESTS_APPOINTMENT_FAILED";

export const POST_PANDEMIC_TEST_RESULT = "POST_PANDEMIC_TEST_RESULT";
export const POST_PANDEMIC_TEST_RESULT_SUCCESS =
  "POST_PANDEMIC_TEST_RESULT_SUCCESS";
export const POST_PANDEMIC_TEST_RESULT_FAILED =
  "POST_PANDEMIC_TEST_RESULT_FAILED";

export const PUT_TESTING = "PUT_TESTING";
export const PUT_TESTING_SUCCESS = "PUT_TESTING_SUCCESS";
export const PUT_TESTING_FAILED = "PUT_TESTING_FAILED";

export const PUT_TEST_CENTRE = "PUT_TEST_CENTRE";
export const PUT_TEST_CENTRE_SUCCESS = "PUT_TEST_CENTRE_SUCCESS";
export const PUT_TEST_CENTRE_FAILED = "PUT_TEST_CENTRE_FAILED";

export const PUT_SCHEDULED_TEST_CENTRE = "PUT_SCHEDULED_TEST_CENTRE";
export const PUT_SCHEDULED_TEST_CENTRE_SUCCESS =
  "PUT_SCHEDULED_TEST_CENTRE_SUCCESS";
export const PUT_SCHEDULED_TEST_CENTRE_FAILED =
  "PUT_SCHEDULED_TEST_CENTRE_FAILED";

export const PUT_TESTS_APPOINTMENT = "PUT_TESTS_APPOINTMENT";
export const PUT_TESTS_APPOINTMENT_SUCCESS = "PUT_TESTS_APPOINTMENT_SUCCESS";
export const PUT_TESTS_APPOINTMENT_FAILED = "PUT_TESTS_APPOINTMENT_FAILED";

export const PUT_PANDEMIC_TEST_RESULT = "PUT_PANDEMIC_TEST_RESULT";
export const PUT_PANDEMIC_TEST_RESULT_SUCCESS =
  "PUT_PANDEMIC_TEST_RESULT_SUCCESS";
export const PUT_PANDEMIC_TEST_RESULT_FAILED =
  "PUT_PANDEMIC_TEST_RESULT_FAILED";

export const GET_SCHEDULED_TEST_CENTRES_BY_INFO =
  "GET_SCHEDULED_TEST_CENTRES_BY_INFO";
export const GET_SCHEDULED_TEST_CENTRES_BY_INFO_SUCCESS =
  "GET_SCHEDULED_TEST_CENTRES_BY_INFO_SUCCESS";
export const GET_SCHEDULED_TEST_CENTRES_BY_INFO_FAILED =
  "GET_SCHEDULED_TEST_CENTRES_BY_INFO_FAILED";
