export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const GET_ORGANIZATIONS_SUCCESS = "GET_ORGANIZATIONS_SUCCESS";
export const GET_ORGANIZATIONS_FAILED = "GET_ORGANIZATIONS_FAILED";

export const REGISTER_ORGANIZATION = "REGISTER_ORGANIZATION";
export const REGISTER_ORGANIZATION_SUCCESS = "REGISTER_ORGANIZATION_SUCCESS";
export const REGISTER_ORGANIZATION_FAILED = "REGISTER_ORGANIZATION_FAILED";

export const REGISTER_ORGANIZATION_PUBLIC = "REGISTER_ORGANIZATION_PUBLIC";
export const REGISTER_ORGANIZATION_PUBLIC_SUCCESS =
  "REGISTER_ORGANIZATION_PUBLIC_SUCCESS";
export const REGISTER_ORGANIZATION_PUBLIC_FAILED =
  "REGISTER_ORGANIZATION_PUBLIC_FAILED";

export const GET_ORGANIZATION_BY_ID = "GET_ORGANIZATION_BY_ID";
export const GET_ORGANIZATION_BY_ID_SUCCESS = "GET_ORGANIZATION_BY_ID_SUCCESS";
export const GET_ORGANIZATION_BY_ID_FAILED = "GET_ORGANIZATION_BY_ID_FAILED";

export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const UPDATE_ORGANIZATION_SUCCESS = "UPDATE_ORGANIZATION_SUCCESS";
export const UPDATE_ORGANIZATION_FAILED = "UPDATE_ORGANIZATION_FAILED";

export const GET_PANDEMIC_CONTACTS = "GET_PANDEMIC_CONTACTS";
export const GET_PANDEMIC_CONTACTS_SUCCESS = "GET_PANDEMIC_CONTACTS_SUCCESS";
export const GET_PANDEMIC_CONTACTS_FAILED = "GET_PANDEMIC_CONTACTS_FAILED";

export const GET_PANDEMIC_CONTACT_BY_ID = "GET_PANDEMIC_CONTACT_BY_ID";
export const GET_PANDEMIC_CONTACT_BY_ID_SUCCESS =
  "GET_PANDEMIC_CONTACT_BY_ID_SUCCESS";
export const GET_PANDEMIC_CONTACT_BY_ID_FAILED =
  "GET_PANDEMIC_CONTACT_BY_ID_FAILED";

export const CREATE_PANDEMIC_CONTACT = "CREATE_PANDEMIC_CONTACT";
export const CREATE_PANDEMIC_CONTACT_SUCCESS =
  "CREATE_PANDEMIC_CONTACT_SUCCESS";
export const CREATE_PANDEMIC_CONTACT_FAILED = "CREATE_PANDEMIC_CONTACT_FAILED";

export const CREATE_PANDEMIC_CONTACT_PUBLIC = "CREATE_PANDEMIC_CONTACT_PUBLIC";
export const CREATE_PANDEMIC_CONTACT_PUBLIC_SUCCESS =
  "CREATE_PANDEMIC_CONTACT_PUBLIC_SUCCESS";
export const CREATE_PANDEMIC_CONTACT_PUBLIC_FAILED =
  "CREATE_PANDEMIC_CONTACT_PUBLIC_FAILED";

export const UPDATE_PANDEMIC_CONTACT = "UPDATE_PANDEMIC_CONTACT";
export const UPDATE_PANDEMIC_CONTACT_SUCCESS =
  "UPDATE_PANDEMIC_CONTACT_SUCCESS";
export const UPDATE_PANDEMIC_CONTACT_FAILED = "UPDATE_PANDEMIC_CONTACT_FAILED";

export const GET_PANDEMIC_CONTACTS_BY_ORG_ID =
  "GET_PANDEMIC_CONTACTS_BY_ORG_ID";
export const GET_PANDEMIC_CONTACTS_BY_ORG_ID_SUCCESS =
  "GET_PANDEMIC_CONTACTS_BY_ORG_ID_SUCCESS";
export const GET_PANDEMIC_CONTACTS_BY_ORG_ID_FAILED =
  "GET_PANDEMIC_CONTACTS_BY_ORG_ID_FAILED";
