export const GET_COVID_NEWS = "GET_COVID_NEWS";
export const GET_COVID_NEWS_SUCCESS = "GET_COVID_NEWS_SUCCESS";
export const GET_COVID_NEWS_FAILED = "GET_COVID_NEWS_FAILED";

export const CREATE_COVID_NEWS = "CREATE_COVID_NEWS";
export const CREATE_COVID_NEWS_SUCCESS = "CREATE_COVID_NEWS_SUCCESS";
export const CREATE_COVID_NEWS_FAILED = "CREATE_COVID_NEWS_FAILED";

export const GET_COVID_NEWS_BY_ID = "GET_COVID_NEWS_BY_ID";
export const GET_COVID_NEWS_BY_ID_SUCCESS = "GET_COVID_NEWS_BY_ID_SUCCESS";
export const GET_COVID_NEWS_BY_ID_FAILED = "GET_COVID_NEWS_BY_ID_FAILED";

export const UPDATE_COVID_NEWS = "UPDATE_COVID_NEWS";
export const UPDATE_COVID_NEWS_SUCCESS = "UPDATE_COVID_NEWS_SUCCESS";
export const UPDATE_COVID_NEWS_FAILED = "UPDATE_COVID_NEWS_FAILED";
